name: weather_app
description: "Weather app project"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

# Specifies the version of the Dart SDK that the package relies on.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter # Specifies the Flutter SDK as a dependency.

  # Additional dependencies required by the app.
  geolocator: ^12.0.0 # For location services.
  geocoding: ^3.0.0 # For converting coordinates to addresses.
  permission_handler: ^11.3.1 # For handling permissions.
  provider: ^6.0.3 # For state management.
  sqflite: ^2.0.0+4 # For SQLite database operations.
  path: ^1.8.0 # For path operations.
  sizer: ^2.0.15
  flutter_dotenv: ^5.0.2
  flutter_glow: ^0.3.0 # For glow effects in the UI.
  http: any # For making HTTP requests.
  intl: any # For internationalization and date formatting.

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  # Additional dependencies required for development and testing.
  chewie: ^1.7.0 # For video player widget.
  chewie_audio: ^1.5.0 # For audio player widget.

  flutter_test:
    sdk: flutter # For running Flutter unit tests.

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # For generating app launcher icons.

# The following section is specific to Flutter packages.
flutter:

  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ # Specifies the directory containing assets.
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Configuration for flutter_launcher_icons package.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/icon.png" # Path to the icon image.
  min_sdk_android: 21 # Minimum Android SDK version.
  remove_alpha_ios: true # Remove alpha channel from iOS icons.
  adaptive_icon_background: "assets/icons/icon-bg.png" # Path to the adaptive icon background.
  adaptive_icon_foreground: "assets/icons/icon-fore.png" # Path to the adaptive icon foreground.
